theme: jekyll-theme-minimal
title: Vladislavs Rudāns
description: Senior Developer — Ruby on Rails, C#, Java, Databases
show_downloads: false
social_links:
  github: vrudan
  linkedin: https://www.linkedin.com/in/vladislavs-rudans-51775712/
